var data = [
[10,4,17,50,25,19,20,25,30,29,30,29],
[30,23,4,7,2,12,31,41,42,30,22,20]
];
var line = new RGraph.Line("chart01", data);

line.Set('chart.background.grid', false);
line.Set('chart.colors', ['rgba(255,0,0,1)', '#181818']);
line.Set('chart.linewidth', 5);
line.Set('chart.hmargin', 5);
line.Set('chart.labels', ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']);
line.Set('chart.gutter.left', 40);
line.Set('chart.text.color', 'white');
line.Set('chart.axis.color', 'white');
line.Set('chart.gutter.bottom', '150');

line.Draw();
