    <script src="/js/RGraph/libraries/RGraph.common.core.js" ></script>

    <script src="/js/RGraph/libraries/RGraph.common.context.js" ></script>
    <script src="/js/RGraph/libraries/RGraph.common.annotate.js" ></script>
    <script src="/js/RGraph/libraries/RGraph.common.tooltips.js" ></script>
    <script src="/js/RGraph/libraries/RGraph.common.zoom.js" ></script>
    <script src="/js/RGraph/libraries/RGraph.common.effects.js" ></script>
    <script src="/js/RGraph/libraries/RGraph.line.js" ></script>

