<?php

function get_face($mood = 'neutral') {
	$faces = array(
		'positive' => array('haha', 'smile', 'big_smile', 'byebye'),
		'neutral' => array('ops'),
		'negative' => array('after_boom'),
	);
	$basePath = '/styles/templates/hoborg/gfx/faces/';
	$randIndex = rand(0, count($faces[$mood])-1);

	return $basePath . $faces[$mood][$randIndex] . '.png';
}
?>
<div class="panel" style="height: 70px;">
	<?php
	$class = "positive";
	$mood = 'neutral';
	switch ($lastBuild['lastBuild']['result']) {
		case 'UNSTABLE':
			$class = 'neutral';
			$mood = 'neutral';
			break;
		case 'SUCCESS':
			$class = 'positive';
			$mood = 'positive';
			break;
		case 'FAIL':
			$class = 'negative';
			$mood = 'negative';
			break;
	}
	?>
	<img height="70" style="float: left; margin: -5px 10px 0px 0px" src="<?php echo get_face($mood); ?>">
	<span class="text-XL <?php echo $class ?>"><?php echo $lastBuild['lastBuild']['result'] ?></span><br />
	<?php echo date('Y.m.d H:i:s', $lastBuild['lastBuild']['timestamp']/1000); ?><br />
</div>
<div class="content">

	<?php
	$testScoreClass = 'positive';
	$testScore = $lastBuild['healthReport'][1]['score'];
	?>
        Tests Result: <span class="text-M <?php echo $testScoreClass; ?>"> <?php echo $testScore; ?> / 100 </span><br />

	<?php
	$healthScore = $lastBuild['healthReport'][0]['score'];
	$healthScoreClass = 'positive';
	if ($healthScoreClass < 75) $healthScoreClass = 'negative';
	?>
	Overall Health: <span class="text-M <?php echo $healthScoreClass; ?>"><?php echo $healthScore; ?> / 100 </span>
</div>
