<html class="dashboard">
<head>
	<link href="/static/styles/hoborglabs/css/dashboard.min.css" media="all" rel="stylesheet" type="text/css" />
	<meta name="viewport" content="initial-scale = 1.0,maximum-scale = 1.0">
</head>
<body>
	<div class="container error">
		<div class="row">
			<div class="span4" style="height: 100%; background-color: #0068ff;">
				<img src="/images/error.png">
			</div>
			<div class="span12">
				<h1 style="margin-top: 65px; color: #F53D00">
					<span class="code">{<?php echo empty($code) ? '404':$code ; ?>}
					</span> oh snap! something went wrong
				</h1>
				<h2>
					Sorry, but the page you want to see caused some problems. Try
					checking the URL for errors.
				</h2>
				<h3 style="margin-top: 20px">
					And if you really want to know, the error message is:<br />
				<code><?php echo $error; ?></code>
				</h3>
			</div>
		</div>
	</div>
</body>
</html>
