<?php
if (empty($widget['body'])) {
	return;
} 

$widget['name'] = empty($widget['name']) ? 'No Name' : $widget['name'];
$widget['footer'] = empty($widget['footer']) ? '' : $widget['footer'];
$widget['body'] = empty($widget['body']) ? '' : $widget['body'];
$widget['size'] = empty($widget['size']) ? 'one-third' : $widget['size'];

$class = 'span5';
switch($widget['size']) {
	case 'message':
		$class = 'short span10';
		break;
	case 'full':
		$class = 'span10';
		break;
}
?>

<div class="header"><?php echo $widget['name']; ?></div>
<div class="body"><?php echo render_widget($widget); ?></div>
<?php if (!empty($widget['footer'])) : ?>
	<div class="footer"><?php echo $widget['footer']; ?></div>
<?php endif; ?>
