<html>
	<head>
		<link href="/styles/templates/hoborg/css/bootstrap.css" media="all" rel="stylesheet" type="text/css" />
		<link href="/styles/templates/hoborg/css/global.css" media="all" rel="stylesheet" type="text/css" />
		<link href="/styles/templates/hoborg/css/dashboard.css" media="all" rel="stylesheet" type="text/css" />
	</head>
	<body>
                <div id="header" class="container">
                        <div class="row">
                                <div class="span4">
                                        <h1>HoborgLabs Dashoboard</h1>
                                </div>
                                <div class="span12">
                                        <ul class="tabs" style="margin-top: 50px;">
                                                <li><a href="/">Home</a></li>
                                                <li><a href="/doc">Documentation</a></li>
                                                <li class="active"><a href="/dashboard.php?conf=demo">Demo</a></li>
                                        </ul>
                                </div>
                        </div>
                </div>
		<div id="dashboard">
		<div class="container">
			<div class="row">
			<?php foreach ($widgets as & $widget) : ?>
				<?php 
				$widget['name'] = empty($widget['name']) ? 'No Name' : $widget['name'];
				$widget['footer'] = empty($widget['footer']) ? '' : $widget['footer'];
				$widget['body'] = empty($widget['body']) ? '' : $widget['body'];
				$widget['size'] = empty($widget['size']) ? 'one-third' : $widget['size'];

				$class = 'span-one-third';
				switch($widget['size']) {
					case 'message':
						$class = 'short span16';
						break;
					case 'full':
						$class = 'span16';
						break;
				}
				?>
				<div class="widget <?echo $class?>">
					<div class="header"><?php echo $widget['name']; ?></div>
					<div class="body"><?php echo render_widget($widget); ?></div>
					<div class="footer"><?php echo $widget['footer']; ?></div>
				</div>
			<?php endforeach; unset($widget); ?>
			</div>
		</div>
		<div id="footer" class="container">
		power by hoborglabs &amp; <em>PH</em>objects.
		</div>
		</div>
	</body>
</html>
