<html>
	<head>
		<link href="/styles/templates/hoborg/css/bootstrap.css" media="all" rel="stylesheet" type="text/css" />
		<link href="/styles/templates/hoborg/css/global.css" media="all" rel="stylesheet" type="text/css" />
		<link href="/styles/templates/hoborg/css/dashboard.css" media="all" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
		<script type="text/javascript" src="/js/jquery/jquery.masonry.min.js"></script>
		<script type="text/javascript" src="/js/hoborg/bus.js"></script>
		<script type="text/javascript" src="/js/hoborg/jquery.widgetManager.js"></script>
		<script type="text/javascript">
		$(document).ready(function() {
		  $('#dashboard .container').masonry({
		    itemSelector: '.widget',
		    columnWidth: 10,
		    isFitWidth: true, 
		    isAnimated: true
		  });
		  $(document).widgetManager({
		    conf: 'demo',
		    callback: function(widget) { $('#dashboard .container').masonry('reload'); }
		  });
		<?php foreach ($widgets as $index => & $widget) : ?>
			<?php if (!empty($widget['reload'])) : ?>
				$('#widget-<?php echo $index; ?>').data('config', {tick: <?php echo $widget['reload']; ?>*1000});
				$(document).widgetManager('addWidget', $('#widget-<?php echo $index; ?>'));
			<?php endif; ?>
		<?php endforeach; unset($widget); ?>
		  $(document).widgetManager('start');
		});
		</script>


		<?php echo $head; ?>
	</head>
	<body>
                <div id="header" class="container">
                        <div class="row">
                                <div class="span4">
                                        <h1>HoborgLabs Dashoboard</h1>
                                </div>
                                <div class="span12">
                                        <ul class="tabs" style="margin-top: 50px;">
                                                <li><a href="/">Home</a></li>
                                                <li><a href="/doc">Documentation</a></li>
                                                <li class="active"><a href="/dashboard.php?conf=demo">Demo</a></li>
                                        </ul>
                                </div>
                        </div>
                </div>
		<div id="dashboard">
		<div class="container">
			<div class="row">
			<?php foreach ($widgets as $index => & $widget) : ?>
				<?php 
				$widget['name'] = empty($widget['name']) ? 'No Name' : $widget['name'];
				$widget['footer'] = empty($widget['footer']) ? '' : $widget['footer'];
				$widget['body'] = empty($widget['body']) ? '' : $widget['body'];
				$widget['size'] = empty($widget['size']) ? 'one-third' : $widget['size'];

				$class = 'span5';
				switch($widget['size']) {
					case 'message':
						$class = 'short span10';
						break;
					case 'full':
						$class = 'span10';
						break;
				}
				?>
				<div class="widget <?echo $class?>" id="widget-<?php echo $index; ?>">
					<div class="header"><?php echo $widget['name']; ?></div>
					<div class="body"><?php echo render_widget($widget); ?></div>
					<?php if (!empty($widget['footer'])) : ?>
						<div class="footer"><?php echo $widget['footer']; ?></div>
					<?php endif; ?>
				</div>
			<?php endforeach; unset($widget); ?>
			</div>
		</div>
		</div>

		<div id="footer" class="container">
			<p>
			power by hoborglabs &amp; <em>PH</em>objects.
			</p>
		</div>
		</div>
	</body>
</html>
