<html class="dashboard">
        <head>
                <link href="<?php echo HD_PUBLIC; ?>/styles/templates/hoborg/css/bootstrap.css" media="all" rel="stylesheet" type="text/css" />
                <link href="<?php echo HD_PUBLIC; ?>/styles/templates/hoborg/css/global.css" media="all" rel="stylesheet" type="text/css" />
        </head>
        <body>
                <div class="container">
                        <div class="row"><div class="span=16">
                        <h1>Oops ... something went wrong</h1>
                        <h2><?php echo $error; ?></h2>
                        </div></div>
                </div>
        </body>
</html>
