<html>
	<head>
		<link href="/styles/templates/hoborg/css/bootstrap.css" media="all" rel="stylesheet" type="text/css" />
		<link href="/styles/templates/hoborg/css/global.css" media="all" rel="stylesheet" type="text/css" />
	</head>
	<body>
		<div id="header">
			<h1>Example HoborgLabs Dashoboard</h1>
		</div>
		<div id="body" class="container">
			<div class="row">
			<?php foreach ($widgets as & $widget) : ?>
				<?php 
				$widget['name'] = empty($widget['name']) ? 'No Name' : $widget['name'];
				$widget['footer'] = empty($widget['footer']) ? '' : $widget['footer'];
				$widget['body'] = empty($widget['body']) ? '' : $widget['body'];
				$widget['size'] = empty($widget['size']) ? 'one-third' : $widget['size'];

				$class = 'span-one-third';
				switch($widget['size']) {
					case 'message':
						$class = 'short span16';
						break;
					case 'full':
						$class = 'span16';
						break;
				}
				?>
				<div class="widget <?echo $class?>">
					<div class="header"><?php echo $widget['name']; ?></div>
					<div class="body"><?php echo render_widget($widget); ?></div>
					<div class="footer"><?php echo $widget['footer']; ?></div>
				</div>
			<?php endforeach; unset($widget); ?>
			</div>
		</div>
		<div id="footer" class="container">
		power by hoborglabs &amp; <em>PH</em>objects.
		</div>
	</body>
</html>
