<!DOCTYPE html>
<html class="dashboard">
	<head>
		<link href="<?php echo $HD_PUBLIC; ?>/static/styles/hoborglabs/css/dashboard.min.css" media="all" rel="stylesheet" type="text/css" />
		<?php foreach($this->widgets as $widget) : ?>
			<?php if ($widget->hasCSS()) : ?>
				<?php foreach ($widget->getCSS() as $css) : ?>
					<link href="/proxy.php?file=<?php echo $css; ?>" media="all" rel="stylesheet" type="text/css" />
				<?php endforeach; ?>
			<?php endif; ?>
		<?php endforeach; ?>

		<script type="text/javascript">
		// setup configuration for dashboard
		var widgets = [];
		var widgetOptions = {
			url: '',
			conf: 'demo',
			defaults: {
				template: <?php echo json_encode(file_get_contents(__DIR__ . '/hoborg.jhtml')); ?>
			}
		};

		// prepare all widget - push configs
		<?php foreach ($this->widgets as $index => & $widget) : ?>
		widgets.push(['<?php echo $widget->getJsClassName(); ?>', <?php echo $widget->getJson(); ?>]);
		<?php endforeach; unset($widget); ?>

		window.Hoborglabs = { Dashboard: {
			widgets: widgets,
			widgetClasses: {},
			widgetOptions: widgetOptions,
			selector: '#dashboard'
		}};
		</script>

		<style>
		.widget--hidden { display: none; }
		</style>
	</head>
	<body class="dashboard">
		<div id="dashboard" class="container" style="padding-top: 10px; margin-right: 10px"></div>

		<!-- JAVASCRIPTS
		include individual widgets JS and main dashboard js.
		-->
		<script src="http://d3js.org/d3.v3.min.js"></script>

		<script type="text/javascript">
		var require = {
			'baseUrl': '/static/scripts/hoborglabs-dev'
		};
		</script>
		<script src="/static/scripts/hoborglabs-dev/require.js" type="text/javascript"></script>
		<?php foreach($this->widgets as $widget) : ?>
			<?php if ($widget->hasJS()) : ?>
				<?php foreach ($widget->getJS() as $js) : ?>
					<script type="text/javascript" src="<?php echo $HD_PUBLIC; ?>/proxy.php?file=<?php echo $js; ?>"></script>
				<?php endforeach; ?>
			<?php endif; ?>
		<?php endforeach; ?>

		<script type="text/javascript" src="<?php echo $HD_PUBLIC; ?>/static/scripts/hoborglabs-dev/dashboard.js"></script>
	</body>
</html>
