<html class="dashboard">
	<head>
		<link href="/styles/templates/hoborg/css/bootstrap.css" media="all" rel="stylesheet" type="text/css" />
		<link href="/styles/templates/hoborg/css/global.css" media="all" rel="stylesheet" type="text/css" />
		<link href="/styles/templates/hoborg/css/dashboard.css" media="all" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
<script type="text/javascript" src="/js/jquery/jquery.masonry.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
  $('.container').masonry({
    itemSelector: '.widget',
    columnWidth: 40,
    isFitWidth: true, 
    isAnimated: true
  });
});
</script>
		<?php echo $head; ?>
	</head>
	<body class="dashboard">
		<div class="container">
			<?php foreach ($widgets as & $widget) : ?>
				<?php
				$widget['name'] = empty($widget['name']) ? 'No Name' : $widget['name'];
				$widget['footer'] = empty($widget['footer']) ? '' : $widget['footer'];
				$widget['body'] = empty($widget['body']) ? '' : $widget['body'];
				$widget['size'] = empty($widget['size']) ? 'one-third' : $widget['size'];

				$class = 'span8';
				switch($widget['size']) {
					case 'message':
						$class = 'short span8';
						break;
					case 'full':
						$class = 'span16';
						break;
				}
				?>
				<div class="widget <?echo $class?>">
					<div class="header"><?php echo $widget['name']; ?></div>
					<div class="body"><?php echo render_widget($widget); ?></div>
					<?php if (!empty($widget['footer'])) : ?>
						<div class="footer"><?php echo $widget['footer']; ?></div>
					<?php endif; ?>
				</div>
			<?php endforeach; unset($widget); ?>
		</div>
	</body>
</html>
